import * as React from "react"

import { ComingSoon } from "@/components/common/coming-soon"
import { Base64Tool } from "@/components/tools/base64"
import { CodeBeautifier } from "@/components/tools/code-beautifier"
import { ColorConverter } from "@/components/tools/color-converter"
import { CronCalculator } from "@/components/tools/cron-calculator"
import { CSSAnimationGenerator } from "@/components/tools/css-animation-generator"
import { CSSBoxShadowGenerator } from "@/components/tools/css-box-shadow-generator"
import { CSSLayoutGenerator } from "@/components/tools/css-layout-generator"
import { CsvJsonConverter } from "@/components/tools/csv-json-converter"
import { FontPairingSuggestions } from "@/components/tools/font-pairing-suggestions"
import { GitCommandGenerator } from "@/components/tools/git-command-generator"
import { HashGenerator } from "@/components/tools/hash-generator"
import { HTTPStatusLookup } from "@/components/tools/http-status-lookup"
import { ImageConverter } from "@/components/tools/image-converter"
import { JsonFormatter } from "@/components/tools/json-formatter"
import { JsonToTypescript } from "@/components/tools/json-to-typescript"
import { JwtDecoder } from "@/components/tools/jwt-decoder"
import { LoremGenerator } from "@/components/tools/lorem-generator"
import { MarkdownTool } from "@/components/tools/markdown"
import { MetaTagGenerator } from "@/components/tools/meta-tag-generator"
import { NumberBaseConverter } from "@/components/tools/number-base-converter"
import { PasswordGenerator } from "@/components/tools/password-generator"
import { Playground } from "@/components/tools/playground"
import { PromptFiller } from "@/components/tools/prompt-filler"
import { QRGenerator } from "@/components/tools/qr-generator"
import { RegexTesterAdvanced } from "@/components/tools/regex-tester"
import { ResponsiveTestingTool } from "@/components/tools/responsive-testing"
import { SEOChecker } from "@/components/tools/seo-checker"
import { SqlFormatterTool } from "@/components/tools/sql-formatter"
import { TextUtilities } from "@/components/tools/text-utilities"
import { TimestampConverter } from "@/components/tools/timestamp-converter"
import { URLEncoder } from "@/components/tools/url-encoder"
import { UUIDGenerator } from "@/components/tools/uuid-generator"

export interface Tool {
  id: string
  title: string
  description: string
  icon: string
  category: string
  path: string
  featured: boolean
  component: React.ComponentType
}

export const TOOL_CATEGORIES = [
  "Developer Tools",
  "Text Tools",
  "Color Tools",
  "Image Tools",
  "Security Tools",
  "Code Formatters",
  "CSS Tools",
  "Input Validators",
  "Data Converters",
  "File Tools",
  "String Encoders",
  "SEO Tools",
  "Design Tools",
  "Font Tools",
  "Video Tools",
  "UI Calculators",
  "Code Optimizers",
  "Data Viewers",
  "Debug Tools",
  "PDF Tools",
  "Productivity Tools",
  "AI Client-side Tools",
  "Math Tools",
] as const

export type ToolCategory = (typeof TOOL_CATEGORIES)[number]

export const TOOLS: Tool[] = [
  // Developer Tools
  {
    id: "uuid-generator",
    title: "UUID Generator",
    description: "Unique ID creator",
    icon: "🆔",
    category: "Developer Tools",
    path: "/tools/uuid-generator",
    featured: true,
    component: UUIDGenerator,
  },
  {
    id: "regex-tester",
    title: "Regex Tester",
    description: "Test regular expressions with live highlighting",
    icon: "🔍",
    category: "Developer Tools",
    path: "/tools/regex-tester",
    featured: true,
    component: RegexTesterAdvanced,
  },
  {
    id: "jwt-decoder",
    title: "JWT Debugger & Generator",
    description: "Decode, verify, and create JWTs",
    icon: "🔓",
    category: "Developer Tools",
    path: "/tools/jwt-decoder",
    featured: true,
    component: JwtDecoder,
  },
  {
    id: "hash-generator",
    title: "Hash Generator",
    description: "Generate MD5, SHA, SHA3, HMAC hashes",
    icon: "🔐",
    category: "Developer Tools",
    path: "/tools/hash-generator",
    featured: false,
    component: HashGenerator,
  },
  {
    id: "qr-generator",
    title: "QR Code Generator",
    description: "QR image encoder",
    icon: "📱",
    category: "Developer Tools",
    path: "/tools/qr-generator",
    featured: true,
    component: QRGenerator,
  },
  {
    id: "json-to-typescript",
    title: "JSON → Code",
    description: "Generate types & validators from JSON",
    icon: "🧩",
    category: "Developer Tools",
    path: "/tools/json-to-typescript",
    featured: false,
    component: JsonToTypescript,
  },
  {
    id: "cron-calculator",
    title: "Cron Calculator",
    description: "Build and validate cron expressions with visualization",
    icon: "⏱️",
    category: "Developer Tools",
    path: "/tools/cron-calculator",
    featured: false,
    component: CronCalculator,
  },
  {
    id: "http-status-lookup",
    title: "HTTP Status Lookup",
    description:
      "Searchable database of HTTP status codes with troubleshooting tips",
    icon: "🌐",
    category: "Developer Tools",
    path: "/tools/http-status-lookup",
    featured: false,
    component: HTTPStatusLookup,
  },
  {
    id: "git-command-generator",
    title: "Git Command Generator",
    description: "Interactive Git command builder with common workflows",
    icon: "📚",
    category: "Developer Tools",
    path: "/tools/git-command-generator",
    featured: false,
    component: GitCommandGenerator,
  },
  {
    id: "responsive-testing",
    title: "Responsive Testing Tool",
    description:
      "Preview websites at different screen sizes and test responsive design",
    icon: "📱",
    category: "Developer Tools",
    path: "/tools/responsive-testing",
    featured: true,
    component: ResponsiveTestingTool,
  },
  {
    id: "playground",
    title: "Playground",
    description:
      "Experiment with JavaScript/TypeScript snippets with live preview",
    icon: "🎮",
    category: "Developer Tools",
    path: "/tools/playground",
    featured: false,
    component: Playground,
  },
  {
    id: "meta-tag-generator",
    title: "Meta Tag Generator",
    description: "Generate SEO meta tags, Open Graph, and Twitter Card tags",
    icon: "🏷️",
    category: "Developer Tools",
    path: "/tools/meta-tag-generator",
    featured: false,
    component: MetaTagGenerator,
  },

  // Text Tools
  {
    id: "lorem-generator",
    title: "Lorem Ipsum Generator",
    description: "Dummy text generator",
    icon: "✍️",
    category: "Text Tools",
    path: "/tools/lorem-generator",
    featured: true,
    component: LoremGenerator,
  },
  {
    id: "text-utilities",
    title: "Text Utilities",
    description: "Word count, case conversion, text comparison and more",
    icon: "📝",
    category: "Text Tools",
    path: "/tools/text-utilities",
    featured: true,
    component: TextUtilities,
  },
  {
    id: "prompt-filler",
    title: "Prompt Filler",
    description:
      "Create and fill prompt templates with variables for AI prompts",
    icon: "💬",
    category: "Text Tools",
    path: "/tools/prompt-filler",
    featured: true,
    component: PromptFiller,
  },
  {
    id: "markdown",
    title: "Markdown",
    description: "Write and preview Markdown with syntax highlighting",
    icon: "📝",
    category: "Text Tools",
    path: "/tools/markdown",
    featured: false,
    component: MarkdownTool,
  },

  // Color Tools
  {
    id: "color-converter",
    title: "Color Converter",
    description:
      "Convert colors between HEX, RGB, HSL formats with palette generator",
    icon: "🎨",
    category: "Color Tools",
    path: "/tools/color-converter",
    featured: true,
    component: ColorConverter,
  },

  // Image Tools
  {
    id: "image-converter",
    title: "Image Format Converter",
    description:
      "Convert images between PNG, JPG, WebP, SVG formats with compression",
    icon: "🖼️",
    category: "Image Tools",
    path: "/tools/image-converter",
    featured: true,
    component: ImageConverter,
  },

  // Security Tools
  {
    id: "password-generator",
    title: "Random Password Generator",
    description: "Secure key generator with customizable options",
    icon: "🔑",
    category: "Security Tools",
    path: "/tools/password-generator",
    featured: true,
    component: PasswordGenerator,
  },

  // Code Formatters
  {
    id: "json-formatter",
    title: "JSON Formatter",
    description: "Prettify and visualize JSON data",
    icon: "📄",
    category: "Code Formatters",
    path: "/tools/json-formatter",
    featured: true,
    component: JsonFormatter,
  },
  {
    id: "code-beautifier",
    title: "Code Beautifier & Minifier",
    description: "Beautify or minify JavaScript, CSS, and HTML code",
    icon: "✨",
    category: "Code Formatters",
    path: "/tools/code-beautifier",
    featured: true,
    component: CodeBeautifier,
  },
  {
    id: "sql-formatter",
    title: "SQL Formatter",
    description: "Format and beautify SQL queries with syntax highlighting",
    icon: "🗄️",
    category: "Code Formatters",
    path: "/tools/sql-formatter",
    featured: false,
    component: SqlFormatterTool,
  },

  // CSS Tools
  {
    id: "css-layout-generator",
    title: "CSS Layout Generator",
    description: "Visual CSS Grid and Flexbox builder with live preview",
    icon: "🎨",
    category: "CSS Tools",
    path: "/tools/css-layout-generator",
    featured: true,
    component: CSSLayoutGenerator,
  },
  {
    id: "css-animation-generator",
    title: "CSS Animation Generator",
    description: "Create smooth CSS animations with keyframes and transitions",
    icon: "🎬",
    category: "CSS Tools",
    path: "/tools/css-animation-generator",
    featured: false,
    component: CSSAnimationGenerator,
  },
  {
    id: "css-box-shadow-generator",
    title: "CSS Box Shadow Generator",
    description: "Create custom shadows with live preview",
    icon: "🌗",
    category: "CSS Tools",
    path: "/tools/css-box-shadow-generator",
    featured: false,
    component: CSSBoxShadowGenerator,
  },

  // Data Converters
  {
    id: "timestamp-converter",
    title: "Unix Timestamp Converter",
    description: "Date/time format converter",
    icon: "⏰",
    category: "Data Converters",
    path: "/tools/timestamp-converter",
    featured: true,
    component: TimestampConverter,
  },
  {
    id: "csv-json-converter",
    title: "JSON ⇄ CSV Converter",
    description: "Convert between CSV and JSON with header support",
    icon: "🧮",
    category: "Data Converters",
    path: "/tools/csv-json-converter",
    featured: false,
    component: CsvJsonConverter,
  },
  {
    id: "number-base-converter",
    title: "Base Converter",
    description:
      "Convert numbers between binary, octal, decimal, hex, and custom bases",
    icon: "🔢",
    category: "Data Converters",
    path: "/tools/number-base-converter",
    featured: false,
    component: NumberBaseConverter,
  },

  // String Encoders
  {
    id: "base64",
    title: "Base64 Encoder/Decoder",
    description: "Text to base64 encoding and decoding",
    icon: "🔐",
    category: "String Encoders",
    path: "/tools/base64",
    featured: true,
    component: Base64Tool,
  },
  {
    id: "url-encoder",
    title: "URL Encoder/Decoder",
    description: "Link-safe format encoding and decoding",
    icon: "🌐",
    category: "String Encoders",
    path: "/tools/url-encoder",
    featured: false,
    component: URLEncoder,
  },

  // Design Tools
  {
    id: "css-triangle-generator-design",
    title: "CSS Triangle Generator",
    description: "Create border-based or clip-path triangles",
    icon: "🔺",
    category: "Design Tools",
    path: "/tools/css-triangle-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "glassmorphism-css-generator-design",
    title: "Glassmorphism CSS Generator",
    description: "Create frosted-glass UI with live preview",
    icon: "🪟",
    category: "Design Tools",
    path: "/tools/glassmorphism-css-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "css-3d-text-generator-design",
    title: "CSS 3D Text Generator",
    description: "Design layered 3D text shadows with CSS",
    icon: "🎭",
    category: "Design Tools",
    path: "/tools/css-3d-text-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "font-pair-previewer-design",
    title: "Font Pair Previewer",
    description: "Preview Google Font pairs for headings and body text",
    icon: "👯",
    category: "Design Tools",
    path: "/tools/font-pairing-suggestions",
    featured: false,
    component: FontPairingSuggestions,
  },
  {
    id: "code-preview-maker-design",
    title: "Code Preview Maker",
    description: "Beautiful code screenshots",
    icon: "📸",
    category: "Design Tools",
    path: "/tools/code-preview-maker",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "svg-css-converter-design",
    title: "SVG ⇄ CSS",
    description: "SVG ↔ CSS data URI & mask",
    icon: "🎨",
    category: "Design Tools",
    path: "/tools/svg-css-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "seo-checker",
    title: "Meta Tag Checker",
    description: "Audit SEO meta tags",
    icon: "🔍",
    category: "SEO Tools",
    path: "/tools/seo-checker",
    featured: false,
    component: SEOChecker,
  },
  {
    id: "social-share-link-generator",
    title: "Social Share Link Generator",
    description: "Social link builder",
    icon: "📱",
    category: "SEO Tools",
    path: "/tools/social-share-link-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "alt-text-checker",
    title: "Alt Text Checker",
    description: "Check images for alt text",
    icon: "🖼️",
    category: "SEO Tools",
    path: "/tools/alt-text-checker",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "broken-link-checker",
    title: "Broken Link Checker",
    description: "Check for dead links",
    icon: "🔗",
    category: "SEO Tools",
    path: "/tools/broken-link-checker",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "html-tag-counter",
    title: "HTML Tag Counter",
    description: "Tag usage stats",
    icon: "📊",
    category: "SEO Tools",
    path: "/tools/html-tag-counter",
    featured: false,
    component: ComingSoon,
  },

  // Additional Developer Tools from JSON
  {
    id: "ulid-generator",
    title: "ULID Generator",
    description: "Sortable unique ID generator",
    icon: "🆔",
    category: "Developer Tools",
    path: "/tools/ulid-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "query-string-json-converter",
    title: "Query String ↔ JSON Converter",
    description: "Convert URL parameters to JSON and vice versa",
    icon: "🔄",
    category: "Developer Tools",
    path: "/tools/query-string-json-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "faker-data-generator",
    title: "Faker / Dummy Data Generator",
    description: "Generate fake JSON or CSV data",
    icon: "📊",
    category: "Developer Tools",
    path: "/tools/faker-data-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "chmod-calculator",
    title: "Chmod Calculator",
    description: "Convert file permissions to rwx, numeric & binary",
    icon: "🔐",
    category: "Developer Tools",
    path: "/tools/chmod-calculator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "code-line-counter",
    title: "Code Line Counter",
    description: "Code length tool",
    icon: "📏",
    category: "Developer Tools",
    path: "/tools/code-line-counter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "keyboard-info-viewer",
    title: "Keyboard Info Viewer",
    description: "Inspect keyCode, code, and visualize keyboard layout",
    icon: "⌨️",
    category: "Developer Tools",
    path: "/tools/keyboard-info-viewer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "slug-generator",
    title: "Slug Generator",
    description: "Convert text into SEO-friendly slugs",
    icon: "🔗",
    category: "Developer Tools",
    path: "/tools/slug-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "svg-to-react-component",
    title: "SVG to React Component",
    description: "Convert SVGs into reusable React components",
    icon: "⚛️",
    category: "Developer Tools",
    path: "/tools/svg-to-react-component",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "css-cursor-viewer",
    title: "CSS Cursor Viewer",
    description: "Live preview of all CSS cursor styles",
    icon: "👆",
    category: "Developer Tools",
    path: "/tools/css-cursor-viewer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "css-specificity-checker",
    title: "CSS Specificity Checker",
    description: "Calculate selector specificity",
    icon: "🎯",
    category: "Developer Tools",
    path: "/tools/css-specificity-checker",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "responsive-font-checker",
    title: "Responsive Font Checker",
    description: "Test font scaling on screens",
    icon: "📱",
    category: "Developer Tools",
    path: "/tools/responsive-font-checker",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "copyright-code-generator",
    title: "Copyright Code Generator",
    description: "Legal footer & license snippet generator",
    icon: "©️",
    category: "Developer Tools",
    path: "/tools/copyright-code-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "data-url-generator",
    title: "Data URL Generator",
    description: "Encode/decode data: URIs locally",
    icon: "🔗",
    category: "Developer Tools",
    path: "/tools/data-url-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "html-jsx-converter",
    title: "HTML ⇄ JSX Converter",
    description: "HTML ↔ JSX with correct attrs & styles",
    icon: "⚛️",
    category: "Developer Tools",
    path: "/tools/html-jsx-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "html-previewer",
    title: "HTML Previewer",
    description: "Sandboxed live HTML preview",
    icon: "👁️",
    category: "Developer Tools",
    path: "/tools/html-previewer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "php-serialize-unserialize",
    title: "PHP Serialize ⇄ Unserialize",
    description: "PHP serialize() ↔ JSON (safe)",
    icon: "🐘",
    category: "Developer Tools",
    path: "/tools/php-serialize-unserialize",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "scss-formatter",
    title: "SCSS Formatter",
    description: "Beautify & minify SCSS",
    icon: "💅",
    category: "Developer Tools",
    path: "/tools/scss-formatter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "semver-calculator",
    title: "Semver Calculator",
    description: "Parse, compare & bump SemVer",
    icon: "📦",
    category: "Developer Tools",
    path: "/tools/semver-calculator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "uid-ulid-decoder",
    title: "UID / ULID Decoder",
    description: "Decode ULID/UUID/ObjectId",
    icon: "🔓",
    category: "Developer Tools",
    path: "/tools/uid-ulid-decoder",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "url-parser",
    title: "URL Parser",
    description: "Inspect, clean & rebuild URLs",
    icon: "🔍",
    category: "Developer Tools",
    path: "/tools/url-parser",
    featured: false,
    component: ComingSoon,
  },

  // Additional Text Tools from JSON
  {
    id: "ascii-art-text-generator",
    title: "ASCII Art Text Generator",
    description: "Convert text into ASCII banner art",
    icon: "🎨",
    category: "Text Tools",
    path: "/tools/ascii-art-text-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "text-case-converter",
    title: "Text Case Converter",
    description: "Upper/lower converter",
    icon: "🔤",
    category: "Text Tools",
    path: "/tools/text-case-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "rot13-encoder-decoder",
    title: "ROT13 Encoder / Decoder",
    description: "Reversible Caesar cipher tool",
    icon: "🔄",
    category: "Text Tools",
    path: "/tools/rot13-encoder-decoder",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "morse-code-translator",
    title: "Morse Code Translator",
    description: "Text to Morse and Morse to Text",
    icon: "📡",
    category: "Text Tools",
    path: "/tools/morse-code-translator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "whitespace-cleaner",
    title: "Whitespace Cleaner",
    description: "Remove extra spaces and lines",
    icon: "🧹",
    category: "Text Tools",
    path: "/tools/whitespace-cleaner",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "text-compressor",
    title: "Text Compressor",
    description: "Compress using RLE and Base64",
    icon: "🗜️",
    category: "Text Tools",
    path: "/tools/text-compressor",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "reading-time-estimator",
    title: "Reading & Speaking Time Estimator",
    description: "Estimate reading time",
    icon: "⏱️",
    category: "Text Tools",
    path: "/tools/reading-time-estimator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "paragraph-sentence-counter",
    title: "Paragraph & Sentence Counter",
    description: "Count text blocks",
    icon: "📊",
    category: "Text Tools",
    path: "/tools/paragraph-sentence-counter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "escape-unescape",
    title: "Escape / Unescape",
    description: "Backslash utilities for JS/JSON/Regex",
    icon: "\\",
    category: "Text Tools",
    path: "/tools/escape-unescape",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "line-sort-dedupe",
    title: "Line Sort & Dedupe",
    description: "Sort, dedupe, count & filter lines",
    icon: "📋",
    category: "Text Tools",
    path: "/tools/line-sort-dedupe",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "text-delimiter",
    title: "Text Delimiter",
    description: "Split/join text with regex & CSV-aware",
    icon: "✂️",
    category: "Text Tools",
    path: "/tools/text-delimiter",
    featured: false,
    component: ComingSoon,
  },

  // Additional Color Tools from JSON
  {
    id: "color-picker-palette-generator",
    title: "Color Picker & Palette Generator",
    description: "Advanced color selection with palette export and favorites",
    icon: "🎨",
    category: "Color Tools",
    path: "/tools/color-picker-palette-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "rgb-to-hex-converter",
    title: "RGB to HEX Converter",
    description: "Color format converter",
    icon: "🔄",
    category: "Color Tools",
    path: "/tools/rgb-to-hex-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "hex-to-rgb-converter",
    title: "HEX to RGB Converter",
    description: "HEX to RGB",
    icon: "🔄",
    category: "Color Tools",
    path: "/tools/hex-to-rgb-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "color-gradient-generator",
    title: "Color Gradient Generator",
    description: "CSS gradient maker",
    icon: "🌈",
    category: "Color Tools",
    path: "/tools/color-gradient-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "color-contrast-checker",
    title: "Color Contrast Checker",
    description: "Check WCAG contrast ratio",
    icon: "♿",
    category: "Color Tools",
    path: "/tools/color-contrast-checker",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "color-relationship-generator",
    title: "Color Relationship Generator",
    description: "Explore complementary, triadic, and analogous palettes",
    icon: "🎨",
    category: "Color Tools",
    path: "/tools/color-relationship-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "color-blindness-simulator",
    title: "Color Blindness Simulator",
    description: "Simulate color perception",
    icon: "👁️",
    category: "Color Tools",
    path: "/tools/color-blindness-simulator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "color-meaning-tool",
    title: "Color Meaning Tool",
    description: "Understand color psychology, symbolism & contrast",
    icon: "🧠",
    category: "Color Tools",
    path: "/tools/color-meaning-tool",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "color-code-validator",
    title: "Color Code Validator",
    description: "Validate HEX, RGB, and HSL values",
    icon: "✅",
    category: "Color Tools",
    path: "/tools/color-code-validator",
    featured: false,
    component: ComingSoon,
  },

  // Additional Image Tools from JSON
  {
    id: "image-compressor",
    title: "Image Compressor",
    description: "Compress images",
    icon: "🗜️",
    category: "Image Tools",
    path: "/tools/image-compressor",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "svg-optimizer",
    title: "SVG Optimizer",
    description: "Clean and minify SVG code",
    icon: "✨",
    category: "Image Tools",
    path: "/tools/svg-optimizer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "favicon-generator",
    title: "Favicon Generator",
    description: "Favicon from text or image",
    icon: "🎨",
    category: "Image Tools",
    path: "/tools/favicon-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "base64-image-optimizer",
    title: "Base64 Image Optimizer",
    description: "Compress base64 image size",
    icon: "🖼️",
    category: "Image Tools",
    path: "/tools/base64-image-optimizer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "image-base64-optimizer",
    title: "Image Base64 Optimizer",
    description: "Compress, resize, and optimize Base64 images in your browser",
    icon: "🖼️",
    category: "Image Tools",
    path: "/tools/image-base64-optimizer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "base64-image-converter",
    title: "Base64 Image Converter",
    description:
      "Encode images to Base64 and decode Base64 to images — offline",
    icon: "🔄",
    category: "Image Tools",
    path: "/tools/base64-image-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "icon-maker",
    title: "Icon Maker (ICO/ICNS & Favicon)",
    description: "Generate ICO, ICNS & favicon packs",
    icon: "🎨",
    category: "Image Tools",
    path: "/tools/icon-maker",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "image-background-remover",
    title: "Image Background Remover",
    description: "AI cutout with transparent PNG",
    icon: "✂️",
    category: "Image Tools",
    path: "/tools/image-background-remover",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "image-extractor",
    title: "Image Extractor",
    description: "Extract images from URL/HTML/ZIP",
    icon: "📦",
    category: "Image Tools",
    path: "/tools/image-extractor",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "svg-extractor",
    title: "SVG Extractor",
    description: "Extract, dedupe & optimize SVGs",
    icon: "🎨",
    category: "Image Tools",
    path: "/tools/svg-extractor",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "text-to-svg-converter",
    title: "Text to SVG Converter",
    description: "Text → SVG with custom fonts",
    icon: "🔤",
    category: "Image Tools",
    path: "/tools/text-to-svg-converter",
    featured: false,
    component: ComingSoon,
  },

  // Additional Security Tools from JSON
  {
    id: "hmac-generator",
    title: "HMAC Generator",
    description: "Generate HMAC with SHA-1, SHA-256, SHA-512",
    icon: "🔐",
    category: "Security Tools",
    path: "/tools/hmac-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "basic-auth-generator",
    title: "Basic Auth Generator",
    description: "Encode credentials into Base64 Authorization",
    icon: "🔑",
    category: "Security Tools",
    path: "/tools/basic-auth-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "bcrypt-generator",
    title: "Bcrypt Generator",
    description: "Secure bcrypt hashing and verifier",
    icon: "🔒",
    category: "Security Tools",
    path: "/tools/bcrypt-generator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "password-strength-checker",
    title: "Password Strength Checker",
    description: "Evaluate password security",
    icon: "💪",
    category: "Security Tools",
    path: "/tools/password-strength-checker",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "bip39-passphrase",
    title: "BIP39 Passphrase",
    description:
      "Generate or inspect BIP39 passphrases locally with entropy & safety tools",
    icon: "🔐",
    category: "Security Tools",
    path: "/tools/bip39-passphrase",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "data-encrypt-decrypt",
    title: "Data Encrypt · Decrypt",
    description: "AES-256 + PBKDF2 + HMAC, in-browser",
    icon: "🔐",
    category: "Security Tools",
    path: "/tools/data-encrypt-decrypt",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "pgp-key-generator",
    title: "PGP Key Generator",
    description: "Generate RSA/ECC OpenPGP keys in-browser",
    icon: "🔑",
    category: "Security Tools",
    path: "/tools/pgp-key-generator",
    featured: false,
    component: ComingSoon,
  },

  // Additional Code Formatters from JSON
  {
    id: "html-formatter",
    title: "HTML Formatter",
    description: "Format and preview HTML code",
    icon: "🌐",
    category: "Code Formatters",
    path: "/tools/html-formatter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "css-formatter",
    title: "CSS Formatter",
    description: "Format and organize CSS code",
    icon: "🎨",
    category: "Code Formatters",
    path: "/tools/css-formatter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "javascript-formatter",
    title: "JavaScript Formatter",
    description: "Beautify JavaScript code",
    icon: "📜",
    category: "Code Formatters",
    path: "/tools/javascript-formatter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "xml-formatter",
    title: "XML Formatter",
    description: "Format and beautify XML",
    icon: "📄",
    category: "Code Formatters",
    path: "/tools/xml-formatter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "graphql-formatter",
    title: "GraphQL Formatter",
    description: "Format, validate, and export GraphQL queries",
    icon: "📊",
    category: "Code Formatters",
    path: "/tools/graphql-formatter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "css-to-scss-sass-converter",
    title: "CSS to SCSS/SASS Converter",
    description: "Convert CSS to SCSS or SASS with nesting",
    icon: "💅",
    category: "Code Formatters",
    path: "/tools/css-to-scss-sass-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "erb-formatter",
    title: "ERB Formatter",
    description: "Beautify & minify ERB safely",
    icon: "💎",
    category: "Code Formatters",
    path: "/tools/erb-formatter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "haml-html-converter",
    title: "HAML ⇄ HTML Converter",
    description: "Bidirectional HAML ↔ HTML conversion",
    icon: "🔄",
    category: "Code Formatters",
    path: "/tools/haml-html-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "css-validator",
    title: "CSS Validator",
    description: "Validate CSS syntax and rules",
    icon: "✅",
    category: "CSS Tools",
    path: "/tools/css-validator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "less-formatter",
    title: "LESS Formatter",
    description: "Beautify & minify LESS",
    icon: "💅",
    category: "CSS Tools",
    path: "/tools/less-formatter",
    featured: false,
    component: ComingSoon,
  },

  // Input Validators from JSON
  {
    id: "html-validator",
    title: "HTML Validator",
    description: "Validate HTML structure",
    icon: "✅",
    category: "Input Validators",
    path: "/tools/html-validator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "json-validator",
    title: "JSON Validator",
    description: "Check if JSON is valid and well-formed",
    icon: "✅",
    category: "Input Validators",
    path: "/tools/json-validator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "xml-validator",
    title: "XML Validator",
    description: "Validate XML syntax and structure",
    icon: "✅",
    category: "Input Validators",
    path: "/tools/xml-validator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "email-validator",
    title: "Email Validator",
    description: "Check if email format is valid",
    icon: "✉️",
    category: "Input Validators",
    path: "/tools/email-validator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "url-validator",
    title: "URL Validator",
    description: "Validate web URLs with regex",
    icon: "🔗",
    category: "Input Validators",
    path: "/tools/url-validator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "credit-card-validator",
    title: "Credit Card Validator",
    description: "Validate card number using Luhn's algorithm",
    icon: "💳",
    category: "Input Validators",
    path: "/tools/credit-card-validator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "favicon-checker",
    title: "Favicon Checker",
    description: "Verify favicon presence",
    icon: "🔍",
    category: "Input Validators",
    path: "/tools/favicon-checker",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "yaml-json-converter",
    title: "YAML to JSON Converter",
    description: "Convert YAML and JSON",
    icon: "🔄",
    category: "Data Converters",
    path: "/tools/yaml-json-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "markdown-html-plaintext-converter",
    title: "Markdown ↔ HTML ↔ Plaintext",
    description: "Convert Markdown to HTML, HTML to Markdown, or plain text",
    icon: "📝",
    category: "Data Converters",
    path: "/tools/markdown-html-plaintext-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "binary-to-decimal-converter",
    title: "Binary to Decimal Converter",
    description: "Binary number conversion",
    icon: "🔢",
    category: "Data Converters",
    path: "/tools/binary-to-decimal-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "hex-ascii-converter",
    title: "Hex ⇄ ASCII Converter",
    description: "Hex ↔ ASCII with hexdump & hashes",
    icon: "🔄",
    category: "Data Converters",
    path: "/tools/hex-ascii-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "php-json-converter",
    title: "PHP ⇄ JSON Converter",
    description: "PHP array/object ↔ JSON (safe)",
    icon: "🐘",
    category: "Data Converters",
    path: "/tools/php-json-converter",
    featured: false,
    component: ComingSoon,
  },

  // File Tools from JSON
  {
    id: "gzip-converter",
    title: "GZip Converter",
    description: "Compress & decompress text/files",
    icon: "🗜️",
    category: "File Tools",
    path: "/tools/gzip-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "base58-encoder-decoder",
    title: "Base58 Encoder / Decoder",
    description: "Convert text to/from Base58",
    icon: "🔐",
    category: "String Encoders",
    path: "/tools/base58-encoder-decoder",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "html-entities-encoder-decoder",
    title: "HTML Entities Encoder/Decoder",
    description: "Escape/unescape HTML",
    icon: "🌐",
    category: "String Encoders",
    path: "/tools/html-entities-encoder-decoder",
    featured: false,
    component: ComingSoon,
  },

  // Font Tools from JSON
  {
    id: "font-previewer",
    title: "Font Previewer",
    description: "Test and preview custom fonts live",
    icon: "🔤",
    category: "Font Tools",
    path: "/tools/font-previewer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "font-ligature-tester",
    title: "Font Ligature Tester",
    description: "Preview ligatures and OpenType features in fonts",
    icon: "✨",
    category: "Font Tools",
    path: "/tools/font-ligature-tester",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "font-fallback-tester",
    title: "Font Fallback Tester",
    description: "Preview how fallback fonts render when primary fonts fail",
    icon: "🔄",
    category: "Font Tools",
    path: "/tools/font-fallback-tester",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "font-line-height-tester",
    title: "Font Line Height Tester",
    description:
      "Visualize and generate line-height styles for better readability",
    icon: "📏",
    category: "Font Tools",
    path: "/tools/font-line-height-tester",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "font-metadata-viewer",
    title: "Font Metadata Viewer",
    description: "Inspect font name, glyphs, features, and coverage",
    icon: "ℹ️",
    category: "Font Tools",
    path: "/tools/font-metadata-viewer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "font-glyph-viewer",
    title: "Font Glyph Viewer",
    description: "Explore full character map of any font",
    icon: "🔤",
    category: "Font Tools",
    path: "/tools/font-glyph-viewer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "font-comparison-tool",
    title: "Font Comparison Tool",
    description: "Compare multiple fonts side-by-side",
    icon: "⚖️",
    category: "Font Tools",
    path: "/tools/font-comparison-tool",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "font-subsetter",
    title: "Font Subsetter",
    description: "Remove unused glyphs from fonts",
    icon: "✂️",
    category: "Font Tools",
    path: "/tools/font-subsetter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "font-converter",
    title: "Font Converter",
    description: "Convert TTF, OTF, and WOFF font formats",
    icon: "🔄",
    category: "Font Tools",
    path: "/tools/font-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "font-pair-previewer",
    title: "Font Pair Previewer",
    description: "Preview Google Font pairs for headings and body text",
    icon: "👯",
    category: "Font Tools",
    path: "/tools/font-pair-previewer",
    featured: false,
    component: ComingSoon,
  },

  // Video Tools from JSON
  {
    id: "screen-recorder",
    title: "Screen Recorder",
    description: "Record screen, crop video, and export in MP4, AVI, MOV",
    icon: "🎥",
    category: "Video Tools",
    path: "/tools/screen-recorder",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "aspect-ratio-calculator",
    title: "Aspect Ratio Calculator",
    description: "Resize with correct proportions",
    icon: "📐",
    category: "UI Calculators",
    path: "/tools/aspect-ratio-calculator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "pixel-to-rem-calculator",
    title: "Pixel to REM Calculator",
    description: "Convert px to rem and vice versa",
    icon: "📏",
    category: "UI Calculators",
    path: "/tools/pixel-to-rem-calculator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "css-clamp-calculator",
    title: "CSS Clamp Calculator",
    description: "Generate responsive font sizes",
    icon: "📊",
    category: "UI Calculators",
    path: "/tools/css-clamp-calculator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "line-height-calculator",
    title: "Line Height Calculator",
    description: "Calculate optimal text spacing",
    icon: "📏",
    category: "UI Calculators",
    path: "/tools/line-height-calculator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "grid-column-width-calculator",
    title: "Grid Column Width Calculator",
    description: "Visualize column spans in CSS Grid",
    icon: "📐",
    category: "UI Calculators",
    path: "/tools/grid-column-width-calculator",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "css-unit-converter",
    title: "CSS Unit Converter",
    description: "Convert px, rem, em, %, vw, vh",
    icon: "🔄",
    category: "UI Calculators",
    path: "/tools/css-unit-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "z-index-conflict-checker",
    title: "Z-Index Conflict Checker",
    description: "Visualize layer stacking order",
    icon: "📚",
    category: "UI Calculators",
    path: "/tools/z-index-conflict-checker",
    featured: false,
    component: ComingSoon,
  },

  // Code Optimizers from JSON
  {
    id: "minify-css",
    title: "Minify CSS",
    description: "Remove whitespace and comments",
    icon: "🗜️",
    category: "Code Optimizers",
    path: "/tools/minify-css",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "minify-javascript",
    title: "Minify JavaScript",
    description: "Strip comments, compress, and mangle",
    icon: "🗜️",
    category: "Code Optimizers",
    path: "/tools/minify-javascript",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "json-minifier",
    title: "JSON Minifier",
    description: "Compact and validate JSON",
    icon: "🗜️",
    category: "Code Optimizers",
    path: "/tools/json-minifier",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "html-minifier",
    title: "HTML Minifier",
    description: "Compress HTML and encode entities",
    icon: "🗜️",
    category: "Code Optimizers",
    path: "/tools/html-minifier",
    featured: false,
    component: ComingSoon,
  },

  // Data Viewers from JSON
  {
    id: "json-to-table-viewer",
    title: "JSON to Table Viewer",
    description: "Convert JSON into a visual table",
    icon: "📊",
    category: "Data Viewers",
    path: "/tools/json-to-table-viewer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "json-size-explorer",
    title: "JSON Size Explorer",
    description: "Measure size of each key in a JSON object",
    icon: "📏",
    category: "Data Viewers",
    path: "/tools/json-size-explorer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "side-by-side-diff-viewer",
    title: "Side-by-Side Diff Viewer",
    description: "Compare text/code side-by-side",
    icon: "🔄",
    category: "Data Viewers",
    path: "/tools/side-by-side-diff-viewer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "json-key-counter",
    title: "JSON Key Counter",
    description: "Count JSON fields",
    icon: "🔢",
    category: "Data Viewers",
    path: "/tools/json-key-counter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "markdown-to-html-previewer",
    title: "Markdown to HTML Previewer",
    description: "Live Markdown to HTML",
    icon: "👁️",
    category: "Data Viewers",
    path: "/tools/markdown-to-html-previewer",
    featured: false,
    component: ComingSoon,
  },

  // Debug Tools from JSON
  {
    id: "device-info",
    title: "Device Info",
    description: "Browser/OS/hardware snapshot & tests",
    icon: "💻",
    category: "Debug Tools",
    path: "/tools/device-info",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "ip-info",
    title: "IP Info",
    description: "Device & network snapshot + public IP",
    icon: "🌐",
    category: "Debug Tools",
    path: "/tools/ip-info",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "user-agent-parser",
    title: "User-Agent Parser",
    description: "Parse UA strings & Client Hints",
    icon: "🔍",
    category: "Debug Tools",
    path: "/tools/user-agent-parser",
    featured: false,
    component: ComingSoon,
  },

  // PDF Tools from JSON
  {
    id: "compare-pdf",
    title: "Compare PDF",
    description: "Visual & text diff for PDFs",
    icon: "📄",
    category: "PDF Tools",
    path: "/tools/compare-pdf",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "html-pdf-converter",
    title: "HTML ↔ PDF Converter",
    description: "HTML → PDF & PDF → HTML, locally",
    icon: "🔄",
    category: "PDF Tools",
    path: "/tools/html-pdf-converter",
    featured: false,
    component: ComingSoon,
  },

  // Productivity Tools from JSON
  {
    id: "pomodoro-timer",
    title: "Pomodoro Timer",
    description: "Custom focus & break timer for deep work",
    icon: "⏱️",
    category: "Productivity Tools",
    path: "/tools/pomodoro-timer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "word-character-counter",
    title: "Word & Character Counter",
    description: "Text length tool",
    icon: "🔢",
    category: "Productivity Tools",
    path: "/tools/word-character-counter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "line-space-counter",
    title: "Line & Space Counter",
    description: "Count text lines",
    icon: "📏",
    category: "Productivity Tools",
    path: "/tools/line-space-counter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "byte-counter",
    title: "Byte Counter",
    description: "File size checker",
    icon: "💾",
    category: "Productivity Tools",
    path: "/tools/byte-counter",
    featured: false,
    component: ComingSoon,
  },

  // AI Client-side Tools from JSON
  {
    id: "ai-sentiment-analyzer",
    title: "AI Sentiment Analyzer",
    description: "Analyze text sentiment instantly, directly in your browser",
    icon: "😊",
    category: "AI Client-side Tools",
    path: "/tools/ai-sentiment-analyzer",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "ai-text-summarizer",
    title: "AI Text Summarizer",
    description: "Summarize long text into clear, concise output",
    icon: "📝",
    category: "AI Client-side Tools",
    path: "/tools/ai-text-summarizer",
    featured: false,
    component: ComingSoon,
  },

  // Math Tools from JSON
  {
    id: "unit-converter",
    title: "Unit Converter",
    description: "Metric ↔ imperial length units",
    icon: "📏",
    category: "Math Tools",
    path: "/tools/unit-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "angle-converter",
    title: "Angle Converter",
    description: "Degrees ↔ radians ↔ arc & more",
    icon: "📐",
    category: "Math Tools",
    path: "/tools/angle-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "temperature-converter",
    title: "Temperature Converter",
    description: "Celsius ↔ Fahrenheit ↔ Kelvin",
    icon: "🌡️",
    category: "Math Tools",
    path: "/tools/temperature-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "weight-converter",
    title: "Weight Converter",
    description: "Metric ↔ imperial weight units",
    icon: "⚖️",
    category: "Math Tools",
    path: "/tools/weight-converter",
    featured: false,
    component: ComingSoon,
  },
  {
    id: "time-converter",
    title: "Time Converter",
    description: "Convert between common time units",
    icon: "⏰",
    category: "Math Tools",
    path: "/tools/time-converter",
    featured: false,
    component: ComingSoon,
  },
]

export const getToolById = (id: string): Tool | undefined => {
  return TOOLS.find((tool) => tool.id === id)
}

export const getToolsByCategory = (category: ToolCategory): Tool[] => {
  return TOOLS.filter((tool) => tool.category === category).sort((a, b) =>
    a.title.localeCompare(b.title)
  )
}

export const getFeaturedTools = (): Tool[] => {
  return TOOLS.filter((tool) => tool.featured).sort((a, b) =>
    a.title.localeCompare(b.title)
  )
}

export const getToolsGroupedByCategory = (): Record<string, Tool[]> => {
  const grouped = TOOLS.reduce(
    (acc, tool) => {
      if (!acc[tool.category]) {
        acc[tool.category] = []
      }
      acc[tool.category].push(tool)
      return acc
    },
    {} as Record<string, Tool[]>
  )

  Object.keys(grouped).forEach((category) => {
    grouped[category].sort((a, b) => a.title.localeCompare(b.title))
  })

  return grouped
}

export const searchTools = (query: string): Tool[] => {
  const lowercaseQuery = query.toLowerCase()
  return TOOLS.filter(
    (tool) =>
      tool.title.toLowerCase().includes(lowercaseQuery) ||
      tool.description.toLowerCase().includes(lowercaseQuery) ||
      tool.category.toLowerCase().includes(lowercaseQuery)
  )
}

export const getToolComponent = (
  toolId: string
): React.ComponentType | null => {
  const tool = getToolById(toolId)
  return tool?.component || null
}

export const getToolStats = () => ({
  totalTools: TOOLS.length,
  totalCategories: TOOL_CATEGORIES.length,
  featuredTools: getFeaturedTools().length,
})
